services:
  # Backend + Frontend service
  - type: web
    name: nimbus-messenger
    env: node
    region: frankfurt
    plan: free
    branch: main
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: node apps/server/dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: 36427af4278b7198dc850c7235c4c85feda7275d89fe3d360c79a1af94579765
      - key: DATABASE_URL
        value: postgresql://nimbus:VMEWWc3q2eUrIIVjbgkBRnDlZv9RRBrg@dpg-d70231p5pdvs738vfg0g-a.frankfurt-postgres.render.com/nimbus_wnbp
      - key: CORS_ORIGINS
        value: "*"
      - key: ENCRYPTION_KEY
        value: 36427af4278b7198dc850c7235c4c85feda7275d89fe3d360c79a1af94579765
      - key: MAX_REGISTRATIONS_PER_IP
        value: "5"
      - key: PORT
        value: "3001"
